title: CSC-151 notes
theme: jekyll-theme-minimal
email: yangxiny@grinnell.edu
logo: Primary_Computer Science Department.png
description: This page will host all the memos I and maybe other mentors created and also the worksheets. 
